exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false
  PrintStackTrace:
    active: false
complexity:
  ComplexCondition:
    threshold: 5
  CyclomaticComplexMethod:
    active: false
style:
  ReturnCount:
    max: 8
  NewLineAtEndOfFile:
    active: false
  UnusedPrivateMember:
    active: false
  MagicNumber:
    active: false
comments:
  EndOfSentenceFormat:
    active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false
empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true
naming:
  MatchingDeclarationName:
    active: false
